In [1]:
import pandas as pd

In [2]:
PATH = 'data/ContingencyDataASARCO.csv'
df_complete = pd.read_csv(PATH, parse_dates=['timestamp'])

In [3]:
OFFSET_HOURS = 3
df_complete['timestamp'] = df_complete['timestamp'] + pd.Timedelta(unit='hours', value=OFFSET_HOURS)

In [4]:
group_asarco = ['stop_reason', 'timecat']
resume_activities = df_complete[group_asarco].groupby(by=group_asarco).\
                                              agg({'timecat': 'count'}).\
                                              rename(columns={'timecat': 'count'}).\
                                              reset_index().\
                                              sort_values('count', ascending=False)

In [5]:
resume_activities.groupby(by=['timecat'])['timecat'].count().rename('count')

timecat
Accidente        2
Demora Nprog    13
Demora Prog      5
Efectivo         2
MARC             9
Mant Nprog      11
Mant Prog        9
Reserva          9
Name: count, dtype: int64

In [6]:
# MARC: Maintenance and Repair Contract
resume_activities[resume_activities['timecat'] == 'MARC']

                      stop_reason timecat  count
54   Sin infraestructura de apoyo    MARC    103
23  INSTALACIÓN SISTEMA TECNOLÓGI    MARC     22
51            SISTEMA MESH COASIN    MARC     19
52                       SMARTCAP    MARC      9
55       Sistema contra incendios    MARC      7
42              Radiocomunicacion    MARC      6
50                    SISTEMA CAS    MARC      6
56     Sistema dispatch - modular    MARC      2
11                 Cambio vidrios    MARC      1

In [8]:
import plotly.express as px

In [18]:
df_translation = pd.read_csv('data/mapped_stop_reasons.csv')

In [34]:
resume_activities_asarco = resume_activities.copy()
asarco_activities = resume_activities['timecat'].unique()
asarco_values = ['Efectivo', 'Demora No Prog', 'Demora Prog', 'Mant No Prog', 'Reserva', 'Mant Prog', 'MARC', 'Accidente']
asarco_mapper = dict(zip(asarco_activities, asarco_values))
resume_activities_asarco['timecat'] = resume_activities_asarco['timecat'].map(asarco_mapper)
resume_activities_asarco = pd.merge(df_translation[['stop_reason', 'manual_parsing']],\
                                    resume_activities_asarco,\
                                    left_on='stop_reason',\
                                    right_on='stop_reason')
resume_activities_asarco = resume_activities_asarco.drop(columns='stop_reason').\
                                                    rename(columns={'manual_parsing': 'event', 'timecat': 'asarco_event'})

In [35]:
resume_activities_asarco

                                     event    asarco_event  count
0                     Colacion en cabina 1     Demora Prog   1253
1                     Colacion en cabina 2     Demora Prog   1076
2                          Cambio de turno     Demora Prog   4192
3                     Carga de combustible  Demora No Prog   1891
4                      Colacion en comedor     Demora Prog   1047
5                 Detenido por somnolencia  Demora No Prog     68
6                    Espera de combustible  Demora No Prog    523
7                 Evacuacion por tronadura  Demora No Prog    172
8                        Evento geotecnico  Demora No Prog     20
9                       Mina en emergencia  Demora No Prog     27
10               Operador fuera del equipo  Demora No Prog   2918
11                         Pista obstruida  Demora No Prog  18090
12                                Polucion  Demora No Prog     14
13               Postura/retiro de cadenas  Demora No Prog      5
14                      Relevo de operador  Demora No Prog    777
15                   Sin equipo de carguio  Demora No Prog   5559
16                                Traslado  Demora No Prog    107
17                     Traslado a colacion     Demora Prog     51
18                                Efectivo        Efectivo  34903
19                           Operativo aux        Efectivo      3
20                               Accidente       Accidente      3
21                     Apoyo a otro equipo    Mant No Prog      5
22         Chequeo neumatico no programado    Mant No Prog     16
23          Cambio neumatico no programado    Mant No Prog      6
24             Cambio neumatico programado       Mant Prog     20
25                          Cambio vidrios            MARC      1
26              Falla electrica imprevista    Mant No Prog     26
27                      Falla motor diesel    Mant No Prog    168
28         Instalacion sistema tecnologico            MARC     22
29                      Inspeccion tecnica       Mant Prog     39
30  Mantenimiento no programado neumaticos    Mant No Prog     39
31   Mantenimiento programado motor diesel       Mant Prog     12
32     Mantenimiento programado neumaticos       Mant Prog     35
33                   Mantencion programada       Mant Prog    173
34                     Mecanica imprevista    Mant No Prog    517
35           Problema de montaje neumatico    Mant No Prog      1
36   Presurizacion neumatico no programado    Mant No Prog     10
37      Presurizacion neumatico programado       Mant Prog      2
38            Pinchazo o rotura neumaticos    Mant No Prog     10
39                       Radiocomunicacion            MARC      6
40                Reparacion de estructura    Mant No Prog      4
41           Reparacion equipo accidentado       Accidente     17
42           Reparacion relleno programado       Mant Prog     53
43                Reparaciones programadas       Mant Prog      1
44                             Sistema cas            MARC      6
45                     Sistema mesh coasin            MARC     19
46                                Smartcap            MARC      9
47            Sin infraestructura de apoyo            MARC    103
48                Sistema contra incendios            MARC      7
49              Sistema dispatch - modular            MARC      2
50                        Torque neumatico       Mant Prog     27
51                  Actividad de seguridad         Reserva     93
52         Botadero/Chancado no programado         Reserva     83
53               Con operador no requerido         Reserva    465
54                Corte de energia externo         Reserva     44
55                           Entrenamiento         Reserva     25
56                               MP10 alto         Reserva    123
57                      Pala no disponible         Reserva    108
58                      Restriccion planta         Reserva      1
59           Sin operador / Fuera de faena         Reserva    303

In [41]:
df_sunburst = resume_activities_asarco[['asarco_event', 'event']].reset_index(drop=True)
df_sunburst['values'] = 1

# Plot the tree
fig = px.sunburst(df_sunburst, path=['asarco_event', 'event'], values='values')
fig.update_layout(font=dict(size=30))
FOR_SAVE = True
if FOR_SAVE:
  SAVE_PATH = 'images/ASARCO_map.png'
  SAVE_SPECS = {'width': 900, 'height': 1000, 'scale': 1}
  fig.write_image(SAVE_PATH, **SAVE_SPECS)

fig